sudo: false

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

install:
  - pip install codecov
  - pip install setuptools
  - pip install scipy
  - pip install numpy
  - pip install .

script:
  - python -m unittest discover -b
  - coverage run -m unittest discover -b

after_script:
  - codecov
